### ISSUE TITLE
Records Not being created unless overwrite enabled.

### ISSUE THREAD

**Issue by samharbison** [vanderbilt-redcap/auto-record-generation#3]
We have a project using the external module who reported records not being created after moving the production. We do not have the overwrite records enabled in the module. A record was created in the first of the two projects in development with a specific ID. The module worked accordingly and created a record in the second project. The project(s) were moved to production and all of the data was deleted. The user created a record in the first project (in production) using the same ID from testing, and a record was NOT created in the second project, as had been done before. We enabled overwrite, and the record was created. Through some testing, I found that it seems that when all data is deleted, the external module does not delete the cache of ID's that have been used to create records in the second project. The following is a list of steps to test the problem. This is easily done using auto-numbering for record IDs in the first project.

1. Create both projects, and set up the external module with overwrite not enabled
2. Create a record in the first project and have the external module create a record in the second project.
3. Delete all of the data (in both projects)
4. Create a record in the first project with the same ID as before; the ID for the record in the second project can be the same or different.
5. You will notice that the record in the second project is not created. A new record in the second project will not be created until a new, unused previously record ID in the first project is used to create a record, or until overwrite is enabled. 

This seems problematic for projects that want to test in dev using the schema they plan to use when in production and do not want to have data that has been migrated overwritten when in production.

**Comment by jasonlones** [comment]
I can confirm this issue.  Only work-around is to use piping or other mechanism in the study id setting.

**Comment by moorejr5** [comment]
We've seen a similar issue on our end of things, as well. There hasn't been time to correct it, yet. But I will be looking into things soon, and hope to have a correction out.

**Comment by mmcev106** [comment]
I just submitted v1.6 for approval, which includes @moorejr5's fix for this issue.  I'll go ahead and close this, but feel free to re-open it if anyone encounters any further issues.
